-- ============================================
-- 1. TABEL KONSENTRASI GAS (UG/M3 + DHT)
-- Endpoint:
-- /rest/v1/tb_konsentrasi_gas
-- ============================================

CREATE TABLE public.tb_konsentrasi_gas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    pm25_ugm3 DOUBLE PRECISION,
    pm10_ugm3 DOUBLE PRECISION,
    co_ugm3 DOUBLE PRECISION,
    no2_ugm3 DOUBLE PRECISION,
    o3_ugm3 DOUBLE PRECISION,

    temperature DOUBLE PRECISION,
    humidity DOUBLE PRECISION
);


-- ============================================
-- 2. TABEL OUTPUT ANALOG SENSOR
-- Endpoint:
-- /rest/v1/tb_analog_out
-- ============================================

CREATE TABLE public.tb_analog_out (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    o3_analog DOUBLE PRECISION,
    pm25_analog DOUBLE PRECISION,
    pm10_analog DOUBLE PRECISION,
    no2_analog DOUBLE PRECISION,
    co_analog DOUBLE PRECISION
);


-- ============================================
-- 3. TABEL ISPU
-- Endpoint:
-- /rest/v1/tb_prediksi_kualitas_udara
-- ============================================

CREATE TABLE public.tb_prediksi_kualitas_udara (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    pm2_5_ispu DOUBLE PRECISION,
    pm10_ispu DOUBLE PRECISION,
    co_ispu DOUBLE PRECISION,
    no2_ispu DOUBLE PRECISION,
    o3_ispu DOUBLE PRECISION
);