-- ============================================================
-- MIGRASI: tb_forecast + tb_alert
-- Untuk pipeline ML (XGBoost forecast + Random Forest klasifikasi
-- ISPU) dan logika alert. Jalankan SEKALI setelah db_airlytics.sql
-- dan policy_rls.sql.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Tabel FORECAST (output model XGBoost, horizon 60 menit)
--    1 baris = 1 titik waktu prediksi (t+1 .. t+60)
--    Satu siklus forecast = generated_at yang sama dengan 60 baris
-- ------------------------------------------------------------
CREATE TABLE public.tb_forecast (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generated_at TIMESTAMPTZ DEFAULT NOW(),   -- kapan model dijalankan
    forecast_at TIMESTAMPTZ NOT NULL,         -- titik waktu prediksi (t+1..t+60)
    pm25_ugm3_pred DOUBLE PRECISION,          -- konsentrasi prediksi
    pm10_ugm3_pred DOUBLE PRECISION,
    co_ugm3_pred DOUBLE PRECISION,
    pm25_ispu_pred DOUBLE PRECISION,          -- konversi ke ISPU (untuk chart)
    pm10_ispu_pred DOUBLE PRECISION,
    co_ispu_pred DOUBLE PRECISION,
    category VARCHAR(20)                      -- Baik/Sedang/Tidak Sehat/...
);

-- Index: dashboard ambil forecast terbaru per generated_at
CREATE INDEX idx_forecast_generated ON public.tb_forecast (generated_at DESC);

-- ------------------------------------------------------------
-- 2. Tabel ALERT (log peringatan: ISPU tinggi, anomali, device offline)
-- ------------------------------------------------------------
CREATE TABLE public.tb_alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    alert_type VARCHAR(20) NOT NULL,          -- ISPU_HIGH | ANOMALY | DEVICE_OFFLINE
    severity VARCHAR(10) NOT NULL,            -- LOW | MEDIUM | HIGH
    message TEXT,
    is_active BOOLEAN DEFAULT TRUE,           -- untuk tombol "sudah dibaca"
    payload JSONB                             -- detail tambahan (nilai, kategori)
);

CREATE INDEX idx_alert_created ON public.tb_alert (created_at DESC);

-- ------------------------------------------------------------
-- 3. RLS (konsisten dengan policy_rls.sql: read + insert boleh,
--    update/delete ditolak untuk publishable key)
-- ------------------------------------------------------------
ALTER TABLE public.tb_forecast ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tb_alert ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_select_tb_forecast" ON public.tb_forecast FOR SELECT USING (true);
CREATE POLICY "allow_insert_tb_forecast" ON public.tb_forecast FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_select_tb_alert" ON public.tb_alert FOR SELECT USING (true);
CREATE POLICY "allow_insert_tb_alert" ON public.tb_alert FOR INSERT WITH CHECK (true);
